server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cdc-sync-engine

  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:cdc-sync-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:localhost:9200}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/cdc_demo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
# Topics configuration (e.g., Debezium prefix 'dbserver1', schema 'public', table 'orders')
cdc:
  topic:
    order: ${CDC_TOPIC_ORDER:dbserver1.public.orders}
